waslab04-Lab 04: Introducció al desenvolupament de WebApps amb Ruby on Rails/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tweets do
    put 'like', on: :member
  end
  root 'tweets#index'
end

waslab04-Lab 04: Introducció al desenvolupament de WebApps amb Ruby on Rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

waslab04-Lab 04: Introducció al desenvolupament de WebApps amb Ruby on Rails/app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :author, length: {minimum: 4}
  validates :content, length: {in: 4..280}

end

waslab04-Lab 04: Introducció al desenvolupament de WebApps amb Ruby on Rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "<h1>It works WASLAB04!</h1>".html_safe
  end
end

waslab04-Lab 04: Introducció al desenvolupament de WebApps amb Ruby on Rails/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy like]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all.order(created_at: :desc)
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        if not session[:created_ids].nil?
          session[:created_ids].push(@tweet.id)
        else
          session[:created_ids] = [@tweet.id]

        end
        format.html { redirect_to root_path, notice: "1Tweet was successfully created." }
        format.json { render :index, status: :created, location: @tweet }
      else
        format.html { redirect_to root_path, notice: "Author is too short (minimum is 4 characters) and Content is too short (minimum is 4 characters)" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet)}
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    if session[:created_ids].nil? || !session[:created_ids].include?(@tweet.id)
      respond_to do |format|
        format.html { redirect_to root_path, notice: "You are not allowed to delete this tweet" }
        format.json { head :forbidden }
        end

    else
      session[:created_ids].delete(@tweet.id)
      @tweet.destroy

     respond_to do |format|
       format.html { redirect_to root_path, notice: "1Tweet was successfully destroyed." }
       format.json { head :no_content }
      end
    end
  end

  #Like tweets
def like
    @tweet.likes += 1
    @tweet.save
    respond_to do |format|
        format.html { redirect_to root_path }
        format.json { head :no_content }
    end
end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:author, :content)
    end
end

waslab04-Lab 04: Introducció al desenvolupament de WebApps amb Ruby on Rails/app/helpers/application_helper.rb
module ApplicationHelper
end

waslab04-Lab 04: Introducció al desenvolupament de WebApps amb Ruby on Rails/app/helpers/tweets_helper.rb
module TweetsHelper
end

waslab04-Lab 04: Introducció al desenvolupament de WebApps amb Ruby on Rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waslab04</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

waslab04-Lab 04: Introducció al desenvolupament de WebApps amb Ruby on Rails/app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <table border-style="0", cellpadding="2">
    <tbody>
      <tr>
        <td>Your name:</td>
        <td>
          <input size="70" type="text" name="tweet[author]" id="tweet_author">
        </td>
        <td></td>
      </tr>
      <tr>
        <td>Your tweet:</td>
        <td>
          <textarea rows="2" cols="70" name="tweet[content]" id="tweet_content"></textarea>
        </td>
        <td>
          <input type="submit" name="commit" value="Tweet!" data-disable-with="Tweet!">
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

waslab04-Lab 04: Introducció al desenvolupament de WebApps amb Ruby on Rails/app/views/tweets/_tweet.html.erb
 <div class="tweetitem" id=tweet.id>
    <div class="likes">
      <span class="numlikes" id="showLikes_<%= tweet.id %>"><%= tweet.likes %></span>
      <br>
      <span class="smallfont">
        people like this
        <span>
          <br>
          <% if session[:created_ids].nil? || !session[:created_ids].include?(tweet.id)%>
          <br>
              <%= button_to 'Like', like_tweet_path(tweet), method: :put %>
        <% else %>
            <p class="destroy" >
            <%= button_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
      <% end %>
          </span>
        </span>

      </div>
      <div class="item">
        <h4>
          <em><%= tweet.author %></em>
           @ <%= tweet.created_at.strftime("%H:%M") %>
        </h4>
        <em><%= tweet.content %></em>
    </div>
  </div>
</div>

waslab04-Lab 04: Introducció al desenvolupament de WebApps amb Ruby on Rails/app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

waslab04-Lab 04: Introducció al desenvolupament de WebApps amb Ruby on Rails/app/views/tweets/index.html.erb
<center><h1>Wall of Tweets - 2022</h1></center>
<br>
<div class="walltweet">
  <%= render 'form', tweet: @tweet %>
</div>

<% if notice %>
<br>
<div class="tweetitem" id="notice">
  <% if notice[0] == "1" %>
    <% notice.slice!(0) %>
    <span style="color: green;"><%= notice %></span>
  <% else %>
    <span style="color: red;"><%= notice %></span>
  <% end %>
</div>
<% end %>

<div id="tweets">
  <% @actual_day = "" %>
  <% @tweets.each do |tweet| %>
   <% @tweeet_day = tweet.created_at.strftime("%A, %B %d, %Y") %>
    <% if @actual_day != @tweeet_day %>
    <h3>
      ......
      <%= @actual_day = @tweeet_day %>
    </h3>
  <% end %>
  <%= render tweet %>
  <% end %>
  </div>

waslab04-Lab 04: Introducció al desenvolupament de WebApps amb Ruby on Rails/app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

waslab04-Lab 04: Introducció al desenvolupament de WebApps amb Ruby on Rails/app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>